import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

  const sidebars: SidebarsConfig = {
    tutorialSidebar: [
      'intro',
      {
        type: 'category',
        label: 'O-1 Виза',
        items: [{type: 'autogenerated', dirName: 'o1'}],
      },
      {
        type: 'category',
        label: 'EB-1 Green Card',
        items: [{type: 'autogenerated', dirName: 'eb1'}],
      },
      {
        type: 'category',
        label: 'Критерии',
        items: [{type: 'autogenerated', dirName: 'kriterii'}],
      },
    ],
  };

  export default sidebars;
